<RoundButton>:
    background_disabled_normal: ''
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [100,]

<SwitchButton>:
    background_disabled_normal: ''
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: (0.203125, 0.59375, 0.855469, 1) if self.active else (0.75, 0.75, 0.75, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<Photon>:
    canvas:
        Color:
            rgba: 0.96, 0.90, 0.32, 1
        Ellipse:
            pos: self.pos
            size: self.size

<Slit>:
    canvas.before:                 
        PushMatrix
        Rotate:         
            angle: self.angle              
            origin: self.center
    canvas: 
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
    canvas.after:
        PopMatrix


<MenuScreen>:

    label_play_button: label_play_button
    label_settings_button: label_settings_button

    FloatLayout:
        id: menu_layout
        size_hint_x: 1 
        size_hint_y: 1
        canvas.before: 
            Color: 
                rgba: (1,1,1,1) 
            Rectangle: 
                size: self.size 
                pos: self.pos

        Label: #Title
			id: title_label
			font_size: 0.08 * self.parent.height
			text: 'Ekert91 Protocol\nSimulator 24' 
			multiline: True
			color: 0, 0, 0, 1
			font_name:'NunitoSans'
			bold: True
			pos_hint: {"center_x": 0.5,"center_y": 0.75} 
			size_hint_x: 0.6
			size_hint_y:0.1 
			halign:"center"
			valign:"middle"

        Button: #PlayButton
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.13, 0.07
            pos_hint: {"center_x":0.5,"center_y":0.5}
            on_release:
                root.manager.transition.direction = 'up'
                root.manager.current = 'game'
            Label: 
                id: label_play_button

                font_size: 0.5 * self.parent.height
                font_name: 'NunitoSans'
                text: 'Play'
                x: self.parent.x
				y: self.parent.y
				size: self.parent.width, self.parent.height

        Button: #TutorialButton
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.13, 0.07
            pos_hint: {"center_x":0.5,"center_y":0.4}
            always_release: True
            on_press:
                root.manager.transition.direction = 'up'
                root.manager.current = 'game'
            on_release:
                root.manager.get_screen('game').tutorial_active = True
                root.manager.get_screen('game').tut_press_source.opacity = 1
                root.manager.get_screen('game').source_animation(root.manager.get_screen('game').source)
                
            Label: 
                font_size: 0.5 * self.parent.height
                font_name: 'NunitoSans'
                text: 'Tutorial'
                x: self.parent.x
				y: self.parent.y
				size: self.parent.width, self.parent.height

        Button: #SettingsButton
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.13, 0.07
            pos_hint: {"center_x":0.5,"center_y":0.3}
            on_release:
                root.manager.transition.direction = 'left'
                root.manager.current = 'settings'

            Label: 
                id: label_settings_button
                font_size: 0.5 * self.parent.height
                font_name: 'NunitoSans'
                text: 'Settings'
                x: self.parent.x
				y: self.parent.y
				size: self.parent.width, self.parent.height

        
        GridLayout: #QCommsUB
			cols: 1
			rows: 1
			size_hint: 0.12, 0.08
			pos_hint: {"center_x": 0.5, "y": 0.1}
			Image: #qcommsub logo 
				source: "QCommsUB.png"
				x: self.parent.x
				y: self.parent.y
				size: self.parent.width, self.parent.height 
            

<SettingsScreen>:

    label_settings: label_settings
    settings_menu_button: settings_menu_button

    FloatLayout:
        id: settings_layout
        size_hint_x: 1 
        size_hint_y: 1
        canvas.before: 
            Color: 
                rgba: (1,1,1,1) 
            Rectangle: 
                size: self.size 
                pos: self.pos

        Label:
            id: label_settings
			font_size: 0.04 * self.parent.height
			text: 'Settings' 
			multiline: True
			color: 0, 0, 0, 1
			font_name:'NunitoSans'
			bold: True
			pos_hint: {"center_x": 0.5,"center_y": 0.8} 
			size_hint_x: 0.6
			size_hint_y:0.1 
			halign:"center"
			valign:"middle"

        BoxLayout: #Languages
			size_hint_x: 0.155
			size_hint_y: 0.07
			pos_hint:{"center_x": 0.5,"center_y": 0.65}
			orientation: "horizontal"
            spacing: 0.02 * self.width

			Button: #Catalan 
	            id: button_cat
	            text: "CAT"
	            font_name:'NunitoSans'
                font_size: 0.4 * self.height
				bold: True
	            background_normal: ''
                background_down: ''
	            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            	halign: 'center'
				valign: 'middle' 
                on_press: root.catalan()

			Button: #Spanish 
	            id: button_esp
	            text: "ESP"
	            font_name:'NunitoSans'
                font_size: 0.4 * self.height
                bold: True
	            background_normal: ''
                background_down: ''
	            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            	halign: 'center'
				valign: 'middle' 
                on_press: root.spanish()
				  
			Button: #English 
	            id: button_eng
	            text: "ENG"
	            font_name:'NunitoSans'
                font_size: 0.4 * self.height
                bold: True
                background_normal: ''
                background_down: ''
	            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
				bold: True
            	halign: 'center'
				valign: 'middle' 
                on_press: root.english()
				

        Button:
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.155, 0.07
            pos_hint: {"center_x":0.5,"center_y":0.2}
            on_press:
                root.manager.transition.direction = 'right'
                root.manager.current = 'menu'

            Label: 
                id: settings_menu_button
                font_size: 0.5 * self.parent.height
                font_name: 'NunitoSans'
                text: 'Menu'
                x: self.parent.x
				y: self.parent.y
				size: self.parent.width, self.parent.height


<E91Simulation>:

    game_menu_button: game_menu_button
    tutorial_box: tutorial_box
    previous_step_button: previous_step_button
    next_step_button: next_step_button

    source: source
    label_source: label_source

    photon_alice_1: photon_alice_1
    photon_alice_2: photon_alice_2
    photon_alice_3: photon_alice_3
    photon_alice_4: photon_alice_4
    photon_alice_5: photon_alice_5
    photon_alice_6: photon_alice_6
    photon_alice_7: photon_alice_7
    photon_alice_8: photon_alice_8
    photon_alice_9: photon_alice_9
    photon_alice_10: photon_alice_10

    photon_bob_1: photon_bob_1
    photon_bob_2: photon_bob_2
    photon_bob_3: photon_bob_3
    photon_bob_4: photon_bob_4
    photon_bob_5: photon_bob_5
    photon_bob_6: photon_bob_6
    photon_bob_7: photon_bob_7
    photon_bob_8: photon_bob_8
    photon_bob_9: photon_bob_9
    photon_bob_10: photon_bob_10

    alice_filter: alice_filter
    bob_filter: bob_filter
    eve_left_filter: eve_left_filter
    eve_right_filter: eve_right_filter

    alice_slit: alice_slit
    bob_slit: bob_slit
    eve_left_slit: eve_left_slit
    eve_right_slit: eve_right_slit

    switch_eve: switch_eve
    label_eavesdropping: label_eavesdropping

    switch_eve_left: switch_eve_left
    switch_eve_right: switch_eve_right

    switch_expert_mode: switch_expert_mode
    label_expert_mode: label_expert_mode

    slider: slider

    tut_press_source: tut_press_source
    tut_emitted: tut_emitted
    tut_alice_button: tut_alice_button
    tut_bob_button: tut_bob_button
    tut_alice_bit: tut_alice_bit
    tut_bob_bit: tut_bob_bit
    tut_eve: tut_eve
    tut_eve_left: tut_eve_left
    tut_eve_right: tut_eve_right
    tut_slider: tut_slider
    tut_eve_expert: tut_eve_expert
    

    FloatLayout:

        id: game_layout
        size_hint_x: 1 
        size_hint_y: 1
        canvas.before: 
            Color: 
                rgba: (1,1,1,1) 
            Rectangle: 
                size: self.size 
                pos: self.pos

        BoxLayout:
			size_hint_x: 0.155
			size_hint_y: 0.05
			pos_hint:{"center_x": 0.5,"center_y": 0.05}
			orientation: "horizontal"
            spacing: 0.02 * self.width

            Button: #Clear
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_press:
                    root.clear()
                Label: 
                    id: game_menu_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Clear'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #KeyButton
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_release:
                    root.manager.transition.direction = 'right'
                    root.manager.current = 'key'
                Label: 
                    id: label_key_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Key'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #back to menu
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_press:
                    root.tutorial_active = False
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'menu'
                    root.stop_tutorial()
                Label: 
                    id: game_menu_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Menu'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height


        BoxLayout:
            id: tutorial_box
			size_hint_x: 0.105
			size_hint_y: 0.05
			pos_hint:{"center_x": 0.67, "center_y": 0.05}
			orientation: "horizontal"
            spacing: 0.028 * self.width
            opacity: 1 if root.tutorial_active else 0

            Button: #<|
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                disabled: False if root.tutorial_active else True
                on_press:
                    root.previous_step_tutorial()
                Label:
                    id: previous_step_button
                    font_size: 0.7 * self.parent.height
                    font_name: 'NunitoSans'
                    text: '<'
                    halign: 'center'
                    x: self.parent.x
                    y: 1.08 * self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #Step
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.75, 0.75, 0.75, 1)
                size_hint: 1.3, 1
                Label: 
                    id: step_number
                    font_size: 0.55 * self.parent.height
                    font_name: 'NunitoSans'
                    text: str(root.tutorial_step)
                    halign: 'center'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #|>
                id: next_step_button
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                disabled: False if root.tutorial_active else True
                on_release:
                    root.next_step_tutorial()
                Label: 
                    id: step_forward_button
                    font_size: 0.7 * self.parent.height
                    font_name: 'NunitoSans'
                    text: ">"
                    halign: 'center'
                    x: self.parent.x
                    y: 1.08 * self.parent.y
                    size: self.parent.width, self.parent.height

            
        SwitchButton:
            id: switch_eve 
            size_hint: 0.045, 0.035
            rgba: (0.75, 0.75, 0.75, 1) if self.active else (0, 0.7, 0.7, 1)
            pos_hint: {"center_x": 0.5,"center_y": 0.7}
            on_press: 
                self.change_mode()
                if root.tutorial_active and root.tutorial_step == 4: root.next_step_tutorial()

            Label:
                color: 0, 0, 0, 1
                center: self.parent.center
                font_size: 0.6 * self.parent.height
                font_name: 'NunitoSans'
                text: "ON" if switch_eve.active else "OFF"
        Label:
            id: label_eavesdropping
            color: 0, 0, 0, 1
            font_size: 0.03 * game_layout.height
            pos_hint: {"center_x": 0.5,"center_y": 0.74}
            font_name: 'NunitoSans'
            text: "Eavesdropping"
        Label:
            color: 0, 0, 0, 1
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            pos_hint: {"center_x": 0.5,"center_y": 0.16}
            text: "Eve" if switch_eve.active else ''

        SwitchButton:
            id: switch_eve_left 
            size_hint: 0.045, 0.035
            opacity: 1 if switch_eve.active else 0
            rgba: (0.75, 0.75, 0.75, 1) if self.active else (0, 0.7, 0.7, 1)
            pos_hint: {"center_x": 0.31,"center_y": (eve_left_filter.top + 0.5 * self.height) / root.height}
            on_press: 
                self.change_mode() if switch_eve.active else ''
                if root.tutorial_active and root.tutorial_step == 5: root.next_step_tutorial()
                
            Label:
                color: 0, 0, 0, 1
                center: self.parent.center
                font_size: 0.6 * self.parent.height
                font_name: 'NunitoSans'
                text: "ON" if self.parent.active else "OFF"

        SwitchButton:
            id: switch_eve_right 
            size_hint: 0.045, 0.035
            opacity: 1 if switch_eve.active else 0
            rgba: (0.75, 0.75, 0.75, 1) if self.active else (0, 0.7, 0.7, 1)
            pos_hint: {"center_x": 0.69,"center_y": (eve_right_filter.top + 0.5 * self.height) / root.height}
            on_press: 
                self.change_mode() if switch_eve.active else ''
                if root.tutorial_active and root.tutorial_step == 6: root.next_step_tutorial()
            Label:
                color: 0, 0, 0, 1
                center: self.parent.center
                font_size: 0.6 * self.parent.height
                font_name: 'NunitoSans'
                text: "ON" if self.parent.active else "OFF"
        
        SwitchButton:
            id: switch_expert_mode 
            size_hint: 0.045, 0.035
            rgba: (0.75, 0.75, 0.75, 1) if self.active else (0, 0.7, 0.7, 1)
            pos_hint: {"center_x": 0.1,"center_y": 0.9}
            on_press: 
                self.change_mode()
                if root.tutorial_active and root.tutorial_step == 8: root.next_step_tutorial()
                
            Label:
                color: 0, 0, 0, 1
                center: self.parent.center
                font_size: 0.6 * self.parent.height
                font_name: 'NunitoSans'
                text: "ON" if switch_expert_mode.active else "OFF"
        Label:
            id: label_expert_mode
            color: 0, 0, 0, 1
            font_size: 0.028 * game_layout.height 
            font_name: 'NunitoSans'
            pos_hint: {"center_x": 0.1,"center_y": 0.94}
            text: "Expert Mode"
        Label:
            color: (0.203125, 0.59375, 0.855469, 1) if alice_slit.angle==0 and bob_slit.angle==-22.5 else (0, 0, 0, 1)
            opacity: 1 if switch_expert_mode.active else 0
            pos_hint: {"center_x": 0.26,"center_y": 0.9}
            font_size: 0.032 * game_layout.height if alice_slit.angle==0 and bob_slit.angle==-22.5 else 0.028 * game_layout.height
            font_name: 'NunitoSans'
            text: "E(a,b) = " + str(root.E_a1b1)
        Label:
            color: (0.203125, 0.59375, 0.855469, 1) if alice_slit.angle==0 and bob_slit.angle==22.5 else (0, 0, 0, 1)
            opacity: 1 if switch_expert_mode.active else 0
            pos_hint: {"center_x": 0.42,"center_y": 0.9}
            font_size: 0.032 * game_layout.height if alice_slit.angle==0 and bob_slit.angle==22.5 else 0.028 * game_layout.height 
            font_name: 'NunitoSans'
            text: "E(a,b') = " + str(root.E_a1b3)
        Label:
            color: (0.203125, 0.59375, 0.855469, 1) if alice_slit.angle==45 and bob_slit.angle==-22.5 else (0, 0, 0, 1)
            opacity: 1 if switch_expert_mode.active else 0
            pos_hint: {"center_x": 0.58,"center_y": 0.9}
            font_size: 0.032 * game_layout.height if alice_slit.angle==45 and bob_slit.angle==-22.5 else 0.028 * game_layout.height 
            font_name: 'NunitoSans'
            text: "E(a',b) = " + str(root.E_a3b1)
        Label:
            color: (0.203125, 0.59375, 0.855469, 1) if alice_slit.angle==45 and bob_slit.angle==22.5 else (0, 0, 0, 1)
            opacity: 1 if switch_expert_mode.active else 0
            pos_hint: {"center_x": 0.74,"center_y": 0.9}
            font_size: 0.032 * game_layout.height if alice_slit.angle==45 and bob_slit.angle==22.5 else 0.028 * game_layout.height 
            font_name: 'NunitoSans'
            text: "E(a',b') = " + str(root.E_a3b3)
        Label:
            color: (0, 0, 0, 1) if root.S < 2 else (160/255, 32/255, 240/255, 1)
            opacity: 1 if switch_expert_mode.active else 0
            pos_hint: {"center_x": 0.9,"center_y": 0.9}
            font_size: 0.032 * game_layout.height if root.S > 2 else 0.028 * game_layout.height 
            font_name: 'NunitoSans'
            text: "S = " + str(root.S)


        Button:
            id: alice_filter
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.1,"center_y": 0.5}
            on_press:
                alice_slit.change_left_angles()
                if root.tutorial_active and root.tutorial_step == 2: root.next_step_tutorial()
        Slit:
            id: alice_slit
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.1,"center_y": 0.5}
        Label:
            id: alice_angle
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.1,"center_y": 0.28}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(alice_slit.angle) + " º"
        Label:
            id: alice_bit
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.1,"center_y": 0.75}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(root.a_bit)
        Label:
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.1,"center_y": 0.16}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: "Alice"

        Button:
            id: bob_filter
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.9,"center_y": 0.5}
            on_press: 
                bob_slit.change_right_angles()
                if root.tutorial_active and root.tutorial_step == 3: root.next_step_tutorial()
        Slit:
            id: bob_slit
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.9,"center_y": 0.5}
        Label:
            id: bob_angle
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.9,"center_y": 0.28}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(bob_slit.angle) + " º"
        Label:
            id: bob_bit
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.9,"center_y": 0.75}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(root.b_bit)
        Label:
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.9,"center_y": 0.16}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: "Bob"

        Button:
            id: eve_left_filter
            background_normal: ''
            background_down: ''
            opacity: 1 if (switch_eve.active and switch_eve_left.active) else 0
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.31,"center_y": 0.5}
            on_press: 
                eve_left_slit.change_left_angles() if switch_eve_left.active else ''
        Slit:
            id: eve_left_slit
            opacity: 1 if (switch_eve.active and switch_eve_left.active) else 0
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.31,"center_y": 0.5}
        Label:
            id: eve_left_angle
            opacity: 1 if (switch_eve.active and switch_eve_left.active) else 0
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.31,"center_y": 0.28}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(eve_left_slit.angle) + " º"
        Label:
            color: 0, 0, 0, 1
            opacity: 1 if (switch_eve.active and switch_eve_left.active) else 0
            pos_hint: {"center_x": 0.31,"center_y": 0.75}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(root.e_left_bit)

        Button:
            id: eve_right_filter
            background_normal: ''
            background_down: ''
            opacity: 1 if (switch_eve.active and switch_eve_right.active) else 0
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.69,"center_y": 0.5}
            on_press: 
                eve_right_slit.change_right_angles() if switch_eve_right.active else ''  
        Slit:
            id: eve_right_slit
            opacity: 1 if (switch_eve.active and switch_eve_right.active) else 0
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.69,"center_y": 0.5}
        Label:
            id: eve_right_angle
            opacity: 1 if (switch_eve.active and switch_eve_right.active) else 0
            color: 0, 0, 0, 1
            pos_hint: {"center_x": 0.69,"center_y": 0.28}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(eve_right_slit.angle) + " º"
        Label:
            color: 0, 0, 0, 1
            opacity: 1 if (switch_eve.active and switch_eve_right.active) else 0
            pos_hint: {"center_x": 0.69,"center_y": 0.75}
            font_size: 0.07 * game_layout.height 
            font_name: 'NunitoSans'
            text: str(root.e_right_bit)
            

        Photon:
            id: photon_alice_1
            opacity: 1
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_2
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_3
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_4
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_5
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_6
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_7
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_8
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_9
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_alice_10
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0

        Photon:
            id: photon_bob_1
            opacity: 1
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_2
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_3
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_4
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_5
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_6
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_7
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_8
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_9
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0
        Photon:
            id: photon_bob_10
            opacity: 0
            size_hint: 0.01, 0.01 * root.width / root.height
            #pos_hint: {"center_x": 0.5,"center_y": 0.5}
            #center: root.center
            pos: 0, 0


        RoundButton:
            id: source
            size_hint: 0.045, 0.045 * root.width / root.height
            pos_hint: {"center_x": 0.5,"center_y": 0.5}
            always_release: True
            on_press: 
                root.emission()
                if root.tutorial_active and root.tutorial_step == 1: root.next_step_tutorial()
        Label:
            id: label_source
            color: 0, 0, 0, 1
            font_size: 0.03 * game_layout.height 
            font_name: 'NunitoSans'
            text: "Source"
            pos_hint: {"center_x": 0.5,"center_y": 0.42}

        Slider:
            id: slider
            min: 1
            max: 1000
            step: 1
            value: 1
            track_color: 0.5, 0, 0.4, 1
            value_track: True
            value_track_color: [0.15, 0.45, 0.8, 1] 
            size_hint: 0.1, 0.04
            cursor_size: 0.022 * game_layout.height, 0.022 * game_layout.height 
            pos_hint: {"center_x": 0.5,"center_y": 0.39}
            on_touch_move:
                root.stop_animation(root.slider) 
                if root.tutorial_active and root.tutorial_step == 7: root.next_step_tutorial()
        Label:
            color: 0, 0, 0, 1
            font_size: 0.02 * game_layout.height 
            pos_hint: {"center_x": 0.5,"center_y": 0.37}
            font_name: 'NunitoSans'
            text: str(slider.value)


        Label:
            id: tut_press_source
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.5, "center_y": 0.57}
            font_name: 'NunitoSans'
            text: "Press me!"
            halign:"center"
			valign:"middle"
        
        Label:
            id: tut_emitted
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.5, "center_y": 0.59}
            font_name: 'NunitoSans'
            text: "You have emitted a pair\nof photons!"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_alice_button
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.1, "center_y": (switch_eve.center_y - 0.02 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "Press here to change\nAlice's basis"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_bob_button
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.9, "center_y": (switch_eve.center_y - 0.02 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "And here to change\nBob's basis"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_alice_bit
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.1, "center_y": (alice_bit.center_y + 0.06 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "These are Alice's bits"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_bob_bit
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.9, "center_y": (bob_bit.center_y + 0.06 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "And these Bob's bits"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_eve
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.5, "center_y": (switch_eve.center_y - 0.04 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "Press here to add an eavesdropper"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_eve_left
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.31, "center_y": switch_eve.center_y / root.height}
            font_name: 'NunitoSans'
            text: "Eve can hear from the left"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_eve_right
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.69, "center_y": switch_eve.center_y / root.height}
            font_name: 'NunitoSans'
            text: "And from the right"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_slider
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.5, "center_y": (slider.center_y - 0.07 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "Slide to choose how many\npairs you send"
            halign:"center"
			valign:"middle"

        Label:
            id: tut_eve_expert
            color: [0.1, 0.45, 0.8, 1]
            opacity: 0
            font_size: 0.022 * game_layout.height
            pos_hint: {"center_x": 0.1, "center_y": (switch_expert_mode.center_y - 0.04 * self.height) / root.height}
            font_name: 'NunitoSans'
            text: "Press here for details"
            halign:"center"
			valign:"middle"

<QKeyScreen>:

    source: source

    photon_alice: photon_alice
    photon_bob: photon_bob

    alice_filter: alice_filter
    bob_filter: bob_filter

    alice_slit: alice_slit
    bob_slit: bob_slit

    alice_basis_1: alice_basis_1
    alice_basis_2: alice_basis_2
    alice_basis_3: alice_basis_3
    alice_basis_4: alice_basis_4
    alice_basis_5: alice_basis_5
    alice_basis_6: alice_basis_6
    alice_basis_7: alice_basis_7
    alice_basis_8: alice_basis_8
    alice_basis_9: alice_basis_9
    alice_basis_10: alice_basis_10

    bob_basis_1: bob_basis_1
    bob_basis_2: bob_basis_2
    bob_basis_3: bob_basis_3
    bob_basis_4: bob_basis_4
    bob_basis_5: bob_basis_5
    bob_basis_6: bob_basis_6
    bob_basis_7: bob_basis_7
    bob_basis_8: bob_basis_8
    bob_basis_9: bob_basis_9
    bob_basis_10: bob_basis_10

    alice_bit_1: alice_bit_1
    alice_bit_2: alice_bit_2
    alice_bit_3: alice_bit_3
    alice_bit_4: alice_bit_4
    alice_bit_5: alice_bit_5
    alice_bit_6: alice_bit_6
    alice_bit_7: alice_bit_7
    alice_bit_8: alice_bit_8
    alice_bit_9: alice_bit_9
    alice_bit_10: alice_bit_10

    bob_bit_1: bob_bit_1
    bob_bit_2: bob_bit_2
    bob_bit_3: bob_bit_3
    bob_bit_4: bob_bit_4
    bob_bit_5: bob_bit_5
    bob_bit_6: bob_bit_6
    bob_bit_7: bob_bit_7
    bob_bit_8: bob_bit_8
    bob_bit_9: bob_bit_9
    bob_bit_10: bob_bit_10
    
    key_bit_1: key_bit_1
    key_bit_2: key_bit_2
    key_bit_3: key_bit_3
    key_bit_4: key_bit_4
    key_bit_5: key_bit_5
    key_bit_6: key_bit_6
    key_bit_7: key_bit_7
    key_bit_8: key_bit_8
    key_bit_9: key_bit_9
    key_bit_10: key_bit_10


    FloatLayout:
        id: key_layout
        size_hint_x: 1 
        size_hint_y: 1
        canvas.before: 
            Color: 
                rgba: (1,1,1,1) 
            Rectangle: 
                size: self.size 
                pos: self.pos


        Button:
            id: alice_filter
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.75, 0.75, 0.75, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.145,"center_y": 0.8}
        Slit:
            id: alice_slit
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.145,"center_y": 0.8}

        Button:
            id: bob_filter
            background_normal: ''
            background_down: ''
            background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.75, 0.75, 0.75, 1)
            size_hint: 0.15, 0.15 * root.width / root.height  
            pos_hint: {"center_x": 0.855,"center_y": 0.8}
        Slit:
            id: bob_slit
            size_hint: 0.13, 0.006
            pos_hint: {"center_x": 0.855,"center_y": 0.8}


        Photon:
            id: photon_alice
            opacity: 1
            size_hint: 0.01, 0.01 * root.width / root.height
            center: root.source.center
        Photon:
            id: photon_bob
            opacity: 1
            size_hint: 0.01, 0.01 * root.width / root.height
            center: root.source.center

        RoundButton:
            id: source
            size_hint: 0.045, 0.045 * root.width / root.height
            pos_hint: {"center_x": 0.5,"center_y": 0.8}
            always_release: True
            on_press: root.sequence_emission()
        
        
        GridLayout:
			size_hint_x: 0.2
			size_hint_y: 0.4
			pos_hint:{"center_x": 0.14,"center_y": 0.35}
            rows: 5
            cols: 1

            Label: 
                color: (0, 0, 0, 1)
                font_size: 0.11 * self.parent.height
                font_name: 'NunitoSans'
                text: "Alice's bases"
            
            Label: 
                color: (0, 0, 0, 1)
                font_size: 0.11 * self.parent.height
                font_name: 'NunitoSans'
                text: "Bob's bases"

            Label: 
                color: (0, 0, 0, 1)
                font_size: 0.11 * self.parent.height
                font_name: 'NunitoSans'
                text: "Alice's bits"

            Label: 
                color: (0, 0, 0, 1)
                font_size: 0.11 * self.parent.height
                font_name: 'NunitoSans'
                text: "Bob's bits"

            Label: 
                color: (0, 0, 0, 1)
                font_size: 0.11 * self.parent.height
                font_name: 'NunitoSans'
                text: "Secret key"


        GridLayout:
            background_color: 0, 0, 0, 0
			size_hint_x: 0.7
			size_hint_y: 0.4
			pos_hint:{"center_x": 0.6,"center_y": 0.35}
            rows: 5
            cols: 10
            col_default_width: 0.064 * self.parent.width
            col_force_default: True
            #row_default_height: 0.05 * self.parent.width
            #row_force_default: True
            spacing: 0.0045 * self.width
            

            # Alice's bases
            Image: 
                id: alice_basis_1
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_2
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_3
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_4
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_5
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_6
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_7
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_8
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_9
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: alice_basis_10
                source: "Filters/filter_black_0.png"
                opacity: 0

            # Bob's bases
            Image: 
                id: bob_basis_1
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_2
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_3
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_4
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_5
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_6
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_7
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_8
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_9
                source: "Filters/filter_black_0.png"
                opacity: 0
            Image: 
                id: bob_basis_10
                source: "Filters/filter_black_0.png"
                opacity: 0

            # Alice's bits
            Label: 
                id: alice_bit_1
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_2
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_3
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_4
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_5
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_6
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_7
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label:
                id: alice_bit_8
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_9
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: alice_bit_10
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"

            # Bob's bits
            Label: 
                id: bob_bit_1
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_2
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_3
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_4
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_5
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_6
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_7
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_8
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_9
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: bob_bit_10
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            
            # Secret key
            Label: 
                id: key_bit_1
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_2
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_3
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_4
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_5
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_6
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_7
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_8
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_9
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
            Label: 
                id: key_bit_10
                opacity: 0
                color: (0, 0, 0, 1)
                font_size: 0.14 * self.parent.height
                font_name: 'NunitoSans'
                text: "0"
                

        BoxLayout:
			size_hint_x: 0.155
			size_hint_y: 0.05
			pos_hint:{"center_x": 0.5,"center_y": 0.05}
			orientation: "horizontal"
            spacing: 0.02 * self.width

            Button: #Clear
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_press:
                    root.clear()
                Label: 
                    id: game_menu_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Clear'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #KeyButton
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_release:
                    root.manager.transition.direction = 'left'
                    root.manager.current = 'game'
                Label: 
                    id: label_key_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Back'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height

            Button: #back to menu
                background_normal: ''
                background_down: ''
                background_color: (0.75, 0.75, 0.75, 1) if self.state=='normal' else (0.203125, 0.59375, 0.855469, 1)
                on_press:
                    root.manager.transition.direction = 'up'
                    root.manager.current = 'menu'
                    # new root.stop_tutorial()
                Label:
                    id: game_menu_button
                    font_size: 0.45 * self.parent.height
                    font_name: 'NunitoSans'
                    text: 'Menu'
                    x: self.parent.x
                    y: self.parent.y
                    size: self.parent.width, self.parent.height
